login:
  username: css,.user-input > input:nth-child(1)
  password: css,div.el-form-item:nth-child(2) > div:nth-child(2) > div:nth-child(1) > input:nth-child(1)
  login_submit: css,.el-button
  logging_text: css,.app > div:nth-child(1) > span:nth-child(1)
  flash_error: css,#app > div > div.middle > div.middle-two > span

dfx_task:
  # 递交任务
  add_task_start: xpath,/html/body/div/section/section/main/div/div/div[1]/button
  #上传工程
  upload_dragged: xpath,//*[@id='app']/section/section/main/div/div[2]/div/form/div[2]/div[2]/div/div/input
  #是否选择上一次选择，选择否
  last_selection: css,.el-message-box__btns > button:nth-child(1) > span:nth-child(1)
  #点击规则集下拉框
  #rulegrop: xpath,/html/body/div[1]/section/section/main/div[1]/div[2]/div/form/div[8]/div/div[3]/div/div/div/div/div/input
  rulegrop: xpath,//*[@id="app"]/section/section/main/div[1]/div[2]/div/form/div[8]/div/div[3]/div/div/div/div/div/input
  #选择规则集
  rulegrop_select: xpath,/html/body/div[4]/div[1]/div[1]/ul/li[11]/span
  #选择对象--全部
  object_all: xpath,//*[@id="app"]/section/section/main/div[1]/div[2]/div/form/div[10]/div/div[1]/label[3]/span[1]/span
  #检查对应——text
  object_text: css,div.bold:nth-child(9) > span:nth-child(1)
  #检测/递交任务按钮
  add_task_finally: xpath,//*[@id="app"]/section/section/main/div[1]/div[4]/button[1]/span
  #检测选择“全部-光学点”，
  object_all_point: xpath,/html/body/div[1]/section/section/main/div[1]/div[2]/div/form/div[10]/div/div[3]/div/div[3]/label/span[2]/span
  #检测是否递交任务成功
  add_task_success_info: css,.app > div:nth-child(1) > span:nth-child(1)


